SPRING_CONFIG_URI: http://192.168.59.74:8888
server:
  port: 8761
spring:
  application:
    name: eureka
  profiles:
    active: dev
  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8888}
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  file: /iflytek/logs/springcloud/${spring.application.name}${server.port}.log